package com.demo.mapper;

import com.demo.dao.PointApply;

public interface PointApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCT_PointApply
     *
     * @mbg.generated Wed Apr 04 10:35:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCT_PointApply
     *
     * @mbg.generated Wed Apr 04 10:35:55 CST 2018
     */
    int insert(PointApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCT_PointApply
     *
     * @mbg.generated Wed Apr 04 10:35:55 CST 2018
     */
    int insertSelective(PointApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCT_PointApply
     *
     * @mbg.generated Wed Apr 04 10:35:55 CST 2018
     */
    PointApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCT_PointApply
     *
     * @mbg.generated Wed Apr 04 10:35:55 CST 2018
     */
    int updateByPrimaryKeySelective(PointApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCT_PointApply
     *
     * @mbg.generated Wed Apr 04 10:35:55 CST 2018
     */
    int updateByPrimaryKey(PointApply record);
}