package com.demo.mapper;

import com.demo.dao.StockDetail;

public interface StockDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_deal
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_deal
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    int insert(StockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_deal
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    int insertSelective(StockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_deal
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    StockDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_deal
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    int updateByPrimaryKeySelective(StockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_deal
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    int updateByPrimaryKey(StockDetail record);
}