package com.demo.mapper;

import com.demo.dao.SubscribeService;

public interface SubscribeServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int insert(SubscribeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int insertSelective(SubscribeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    SubscribeService selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int updateByPrimaryKeySelective(SubscribeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int updateByPrimaryKey(SubscribeService record);
}