package com.demo.mapper;

import com.demo.dao.SubscribeServiceSategory;

public interface SubscribeServiceSategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service_category
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service_category
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int insert(SubscribeServiceSategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service_category
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int insertSelective(SubscribeServiceSategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service_category
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    SubscribeServiceSategory selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service_category
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int updateByPrimaryKeySelective(SubscribeServiceSategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_service_category
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int updateByPrimaryKey(SubscribeServiceSategory record);
}