package com.demo.mapper;

import com.demo.dao.SubscribeRelation;

public interface SubscribeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_relation
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_relation
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int insert(SubscribeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_relation
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int insertSelective(SubscribeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_relation
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    SubscribeRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_relation
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int updateByPrimaryKeySelective(SubscribeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe_relation
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    int updateByPrimaryKey(SubscribeRelation record);
}