package com.alibaba.webx.tutorial1.app1.dao.impl;

import com.alibaba.webx.tutorial1.app1.dao.TokenDAO;
import com.alibaba.webx.tutorial1.app1.vo.Token;
import com.alibaba.webx.tutorial1.app1.vo.TokenExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TokenDAOImpl extends SqlMapClientDaoSupport implements TokenDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public TokenDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int countByExample(TokenExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_token.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int deleteByExample(TokenExample example) {
        int rows = getSqlMapClientTemplate().delete("t_token.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        Token _key = new Token();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_token.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public void insert(Token record) {
        getSqlMapClientTemplate().insert("t_token.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public void insertSelective(Token record) {
        getSqlMapClientTemplate().insert("t_token.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<Token> selectByExample(TokenExample example) {
        List<Token> list = getSqlMapClientTemplate().queryForList("t_token.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public Token selectByPrimaryKey(Integer id) {
        Token _key = new Token();
        _key.setId(id);
        Token record = (Token) getSqlMapClientTemplate().queryForObject("t_token.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int updateByExampleSelective(Token record, TokenExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_token.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int updateByExample(Token record, TokenExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_token.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int updateByPrimaryKeySelective(Token record) {
        int rows = getSqlMapClientTemplate().update("t_token.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    public int updateByPrimaryKey(Token record) {
        int rows = getSqlMapClientTemplate().update("t_token.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_token
     *
     * @mbggenerated Fri Aug 19 12:32:31 CST 2016
     */
    protected static class UpdateByExampleParms extends TokenExample {
        private Object record;

        public UpdateByExampleParms(Object record, TokenExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}