package com.demo.entityTmp;

import java.util.Date;

public class MobileTagValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.id
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.appId
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.project
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.name
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.title
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.threshold
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Integer threshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.type
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.statistics
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Boolean statistics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.owners
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private String owners;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.create_mis
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private String createMis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.update_mis
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private String updateMis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.status
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.createtime
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapi_config.updatetime
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.id
     *
     * @return the value of mapi_config.id
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.id
     *
     * @param id the value for mapi_config.id
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.appId
     *
     * @return the value of mapi_config.appId
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.appId
     *
     * @param appid the value for mapi_config.appId
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.project
     *
     * @return the value of mapi_config.project
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.project
     *
     * @param project the value for mapi_config.project
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setProject(String project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.name
     *
     * @return the value of mapi_config.name
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.name
     *
     * @param name the value for mapi_config.name
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.title
     *
     * @return the value of mapi_config.title
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.title
     *
     * @param title the value for mapi_config.title
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.threshold
     *
     * @return the value of mapi_config.threshold
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.threshold
     *
     * @param threshold the value for mapi_config.threshold
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.type
     *
     * @return the value of mapi_config.type
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.type
     *
     * @param type the value for mapi_config.type
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.statistics
     *
     * @return the value of mapi_config.statistics
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Boolean getStatistics() {
        return statistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.statistics
     *
     * @param statistics the value for mapi_config.statistics
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setStatistics(Boolean statistics) {
        this.statistics = statistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.owners
     *
     * @return the value of mapi_config.owners
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public String getOwners() {
        return owners;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.owners
     *
     * @param owners the value for mapi_config.owners
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setOwners(String owners) {
        this.owners = owners;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.create_mis
     *
     * @return the value of mapi_config.create_mis
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public String getCreateMis() {
        return createMis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.create_mis
     *
     * @param createMis the value for mapi_config.create_mis
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setCreateMis(String createMis) {
        this.createMis = createMis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.update_mis
     *
     * @return the value of mapi_config.update_mis
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public String getUpdateMis() {
        return updateMis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.update_mis
     *
     * @param updateMis the value for mapi_config.update_mis
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setUpdateMis(String updateMis) {
        this.updateMis = updateMis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.status
     *
     * @return the value of mapi_config.status
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.status
     *
     * @param status the value for mapi_config.status
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.createtime
     *
     * @return the value of mapi_config.createtime
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.createtime
     *
     * @param createtime the value for mapi_config.createtime
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapi_config.updatetime
     *
     * @return the value of mapi_config.updatetime
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapi_config.updatetime
     *
     * @param updatetime the value for mapi_config.updatetime
     *
     * @mbg.generated Wed Jul 17 17:07:52 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}