package com.demo.dao;

import java.math.BigDecimal;
import java.util.Date;

public class StockDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.id
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.stock_id
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private String stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.deal_time
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Date dealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.deal_price
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private BigDecimal dealPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.deal_hands
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Integer dealHands;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.bs
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Byte bs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.up_down
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Byte upDown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.unknow1
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Integer unknow1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.unknow2
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Integer unknow2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_deal.unknow3
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    private Integer unknow3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.id
     *
     * @return the value of stock_deal.id
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.id
     *
     * @param id the value for stock_deal.id
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.stock_id
     *
     * @return the value of stock_deal.stock_id
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.stock_id
     *
     * @param stockId the value for stock_deal.stock_id
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.deal_time
     *
     * @return the value of stock_deal.deal_time
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.deal_time
     *
     * @param dealTime the value for stock_deal.deal_time
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.deal_price
     *
     * @return the value of stock_deal.deal_price
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.deal_price
     *
     * @param dealPrice the value for stock_deal.deal_price
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setDealPrice(BigDecimal dealPrice) {
        this.dealPrice = dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.deal_hands
     *
     * @return the value of stock_deal.deal_hands
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Integer getDealHands() {
        return dealHands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.deal_hands
     *
     * @param dealHands the value for stock_deal.deal_hands
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setDealHands(Integer dealHands) {
        this.dealHands = dealHands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.bs
     *
     * @return the value of stock_deal.bs
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Byte getBs() {
        return bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.bs
     *
     * @param bs the value for stock_deal.bs
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setBs(Byte bs) {
        this.bs = bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.up_down
     *
     * @return the value of stock_deal.up_down
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Byte getUpDown() {
        return upDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.up_down
     *
     * @param upDown the value for stock_deal.up_down
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setUpDown(Byte upDown) {
        this.upDown = upDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.unknow1
     *
     * @return the value of stock_deal.unknow1
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Integer getUnknow1() {
        return unknow1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.unknow1
     *
     * @param unknow1 the value for stock_deal.unknow1
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setUnknow1(Integer unknow1) {
        this.unknow1 = unknow1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.unknow2
     *
     * @return the value of stock_deal.unknow2
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Integer getUnknow2() {
        return unknow2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.unknow2
     *
     * @param unknow2 the value for stock_deal.unknow2
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setUnknow2(Integer unknow2) {
        this.unknow2 = unknow2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_deal.unknow3
     *
     * @return the value of stock_deal.unknow3
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public Integer getUnknow3() {
        return unknow3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_deal.unknow3
     *
     * @param unknow3 the value for stock_deal.unknow3
     *
     * @mbg.generated Wed Mar 28 20:46:35 CST 2018
     */
    public void setUnknow3(Integer unknow3) {
        this.unknow3 = unknow3;
    }
}