package com.demo.dao;

public class SubscribeServiceSategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_service_category.id
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_service_category.name
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_service_category.is_enabled
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    private Boolean isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_service_category.sequence
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    private Short sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_service_category.create_time
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe_service_category.update_time
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_service_category.id
     *
     * @return the value of t_subscribe_service_category.id
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_service_category.id
     *
     * @param id the value for t_subscribe_service_category.id
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_service_category.name
     *
     * @return the value of t_subscribe_service_category.name
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_service_category.name
     *
     * @param name the value for t_subscribe_service_category.name
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_service_category.is_enabled
     *
     * @return the value of t_subscribe_service_category.is_enabled
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_service_category.is_enabled
     *
     * @param isEnabled the value for t_subscribe_service_category.is_enabled
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_service_category.sequence
     *
     * @return the value of t_subscribe_service_category.sequence
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public Short getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_service_category.sequence
     *
     * @param sequence the value for t_subscribe_service_category.sequence
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public void setSequence(Short sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_service_category.create_time
     *
     * @return the value of t_subscribe_service_category.create_time
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_service_category.create_time
     *
     * @param createTime the value for t_subscribe_service_category.create_time
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe_service_category.update_time
     *
     * @return the value of t_subscribe_service_category.update_time
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe_service_category.update_time
     *
     * @param updateTime the value for t_subscribe_service_category.update_time
     *
     * @mbggenerated Thu Aug 25 12:37:38 CST 2016
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}